---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - wget
      - unzip
      - apt-transport-https
      - software-properties-common
      - python3
      - python3-pip
    state: present
  
- name: Install Python packages
  pip:
    name:
      - Flask
      - structlog
    executable: pip3

